export const CLIENT_CONNECT_REQUEST = "CLIENT_CONNECT_REQUEST";
export const CLIENT_CONNECT_SUCCESS = "CLIENT_CONNECT_SUCCESS";
export const CLIENT_CONNECT_FAIL = "CLIENT_CONNECT_FAIL";
export const CLIENT_SIGNOUT = "CLIENT_SIGNOUT";

export const CLIENT_REGISTER_FAIL = "CLIENT_REGISTER_FAIL";
export const CLIENT_REGISTER_REQUEST = "CLIENT_REGISTER_REQUEST";
export const CLIENT_REGISTER_SUCCESS = "CLIENT_REGISTER_SUCCESS";
