export const COMMANDER_REQUEST = "COMMANDER_REQUEST";
export const COMMANDER_SUCCESS = "COMMANDER_SUCCESS";
export const COMMANDER_FAIL = "COMMANDER_FAIL";
export const COMMANDER_RESET = "COMMANDER_RESET";

export const COMMANDER_VIEW_REQUEST = "COMMANDER_VIEW_REQUEST";
export const COMMANDER_VIEW_SUCCESS = "COMMANDER_VIEW_SUCCESS";
export const COMMANDER_VIEW_FAIL = "COMMANDER_VIEW_FAIL";

export const COMMANDER_PAY_REQUEST = "COMMANDER_PAY_REQUEST";
export const COMMANDER_PAY_SUCCESS = "COMMANDER_PAY_SUCCESS";
export const COMMANDER_PAY_FAIL = "COMMANDER_PAY_FAIL";
export const COMMANDER_PAY_RESET = "COMMANDER_PAY_RESET";

export const COMMANDER_MINE_LIST_REQUEST = "COMMANDER_MINE_LIST_REQUEST";
export const COMMANDER_MINE_LIST_FAIL = "COMMANDER_MINE_LIST_FAIL";
export const COMMANDER_MINE_LIST_SUCCESS = "COMMANDER_MINE_LIST_SUCCESS";
