export const PANIER_AJOUTER_PRODUIT = "PANIER_AJOUTER_PRODUIT";
export const PANIER_SUPPRIMER_PRODUIT = "PANIER_SUPPRIMER_PRODUIT";
export const PANIER_SAVE_SHIPPING_ADDRESS = "PANIER_SAVE_SHIPPING_ADDRESS";
export const PANIER_SAVE_PAIEMENT = "PANIER_SAVE_PAIEMENT";
export const PANIER_VIDE = "PANIER_VIDE";
