export const PRODUIT_LIST_REQUEST = "PRODUIT_LIST_REQUEST";
export const PRODUIT_LIST_SUCCESS = "PRODUIT_LIST_SUCCESS";
export const PRODUIT_LIST_FAIL = "PRODUIT_LIST_FAIL";

export const PRODUIT_DETAILS_REQUEST = "PRODUIT_DETAILS_REQUEST";
export const PRODUIT_DETAILS_SUCCESS = "PRODUIT_DETAILS_SUCCESS";
export const PRODUIT_DETAILS_FAIL = "PRODUIT_DETAILS_FAIL";

export const PRODUIT_CREATE_REQUEST = "PRODUIT_CREATE_REQUEST";
export const PRODUIT_CREATE_SUCCESS = "PRODUIT_CREATE_SUCCESS";
export const PRODUIT_CREATE_FAIL = "PRODUIT_CREATE_FAIL";
export const PRODUIT_CREATE_RESET = "PRODUIT_CREATE_RESET";

export const PRODUIT_UPDATE_REQUEST = "PRODUIT_UPDATE_REQUEST";
export const PRODUIT_UPDATE_SUCCESS = "PRODUIT_UPDATE_SUCCESS";
export const PRODUIT_UPDATE_FAIL = "PRODUIT_UPDATE_FAIL";
export const PRODUIT_UPDATE_RESET = "PRODUIT_UPDATE_RESET";

export const PRODUIT_DELETE_REQUEST = "PRODUIT_DELETE_REQUEST";
export const PRODUIT_DELETE_FAIL = "PRODUIT_DELETE_FAIL";
export const PRODUIT_DELETE_SUCCESS = "PRODUIT_DELETE_SUCCESS";
export const PRODUIT_DELETE_RESET = "PRODUIT_DELETE_RESET";

export const PRODUIT_CATEGORIE_LIST_REQUEST = "PRODUIT_CATEGORIE_LIST_REQUEST";
export const PRODUIT_CATEGORIE_LIST_SUCCESS = "PRODUIT_CATEGORIE_LIST_SUCCESS";
export const PRODUIT_CATEGORIE_LIST_FAIL = "PRODUIT_CATEGORIE_LIST_FAIL";

export const PRODUIT_REVIEW_CREATE_REQUEST = "PRODUIT_REVIEW_CREATE_REQUEST";
export const PRODUIT_REVIEW_CREATE_SUCCESS = "PRODUIT_REVIEW_CREATE_SUCCESS";
export const PRODUIT_REVIEW_CREATE_FAIL = "PRODUIT_REVIEW_CREATE_FAIL";
export const PRODUIT_REVIEW_CREATE_RESET = "PRODUIT_REVIEW_CREATE_RESET";
