const data = {
  produits: [
    {
      _id: "1",
      nom: "Produit en Bois 1",
      categorie: "Bois",
      stock: 10,
      image: "/images/DSC_0255.JPG",
      prix: 20,
      rating: 4.5,
      description: "produit de qualite",
      numReviews: 15,
    },
    {
      _id: "2",
      nom: "Produit en Bois 2",
      categorie: "Bois",
      stock: 20,
      image: "/images/DSC_0266.JPG",
      prix: 35,
      rating: 4.5,
      description: "produit de qualite",
      numReviews: 19,
    },
    {
      _id: "3",
      nom: "Produit en Bois 3",
      categorie: "Bois",
      stock: 12,
      image: "/images/DSC_0267.JPG",
      prix: 29,
      rating: 4.5,
      description: "produit de qualite",
      numReviews: 22,
    },
    {
      _id: "4",
      nom: "Produit en Bois 4",
      categorie: "Bois",
      stock: 13,
      image: "/images/DSC_0271.JPG",
      prix: 70,
      rating: 4.5,
      description: "produit de qualite",
      numReviews: 25,
    },
    {
      _id: "5",
      nom: "Produit en Bois 5",
      categorie: "Bois",
      stock: 10,
      image: "/images/DSC_0273.JPG",
      prix: 50,
      rating: 2,
      description: "produit de qualite",
      numReviews: 16,
    },
    {
      _id: "6",
      nom: "Produit en Bois 6",
      categorie: "Bois",
      stock: 36,
      image: "/images/DSC_0274.JPG",
      prix: 20,
      rating: 5,
      description: "produit de qualite",
      numReviews: 14,
    },
  ],
};

export default data;
